### ISSUE TITLE
项目集成这个包，上架小米和华为应用市场因检测到多次闪退被拒。

### ISSUE THREAD

**Issue by cavanlee** [rongcloud/rongcloud-im-flutter-sdk#120]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
Android,小米手机，具体机型审核人员没反馈，但是提供了FC Log 文件。
```
RongIMLib:Looking for lib/armeabi-v7a/libdl.so in APK /data/app/com.manmolly.merchant-2/base.apk...
06-06 00:02:57.101  6945  6945 D RongLog : [RongLog][ NativeObject ] load RongIMLib:Looking for lib/armeabi/libdl.so in APK /data/app/com.manmolly.merchant-2/base.apk...
06-06 00:02:57.101  6945  6945 D RongLog : [RongLog][ NativeObject ] load RongIMLib:Looking for lib/arm64-v8a/libdl.so in APK /data/app/com.manmolly.merchant-2/base.apk...
06-06 00:02:57.102  6945  6945 D RongLog : [RongLog][ NativeObject ] load RongIMLib:Looking for lib/armeabi-v7a/libdl.so in APK /data/app/com.manmolly.merchant-2/base.apk...
06-06 00:02:57.102  6945  6945 D RongLog : [RongLog][ NativeObject ] load RongIMLib:Looking for lib/armeabi/libdl.so in APK /data/app/com.manmolly.merchant-2/base.apk...
06-06 00:02:57.102  6945  6945 D RongLog : [RongLog][ NativeObject ] load RongIMLib:Looking for lib/arm64-v8a/libdl.so in APK /data/app/com.manmolly.merchant-2/base.apk...
06-06 00:02:57.103  6945  6945 D RongLog : [RongLog][ NativeObject ] load RongIMLib:Looking for lib/armeabi-v7a/libdl.so in APK /data/app/com.manmolly.merchant-2/base.apk...
06-06 00:02:57.103  6945  6945 D RongLog : [RongLog][ NativeObject ] load RongIMLib:Looking for lib/armeabi/libdl.so in APK /data/app/com.manmolly.merchant-2/base.apk...
06-06 00:02:57.104  6945  6945 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-06 00:02:57.105  6945  6945 E AndroidRuntime: FATAL EXCEPTION: main
06-06 00:02:57.105  6945  6945 E AndroidRuntime: Process: com.manmolly.merchant:ipc, PID: 6945
06-06 00:02:57.105  6945  6945 E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service io.rong.imlib.ipc.RongService@a8d337 with Intent { cmp=com.manmolly.merchant/io.rong.imlib.ipc.RongService (has extras) }: io.rong.imlib.relinker.MissingLibraryException: libdl.so
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3281)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6337)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: Caused by: io.rong.imlib.relinker.MissingLibraryException: libdl.so
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.b.a(SourceFile:38)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.d(SourceFile:15)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.a(SourceFile:8)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.a(SourceFile:4)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.d(SourceFile:21)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.a(SourceFile:8)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.a(SourceFile:4)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at io.rong.imlib.NativeObject.<init>(SourceFile:3)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at ad.Yd.a(SourceFile:19)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at ad.hc.<init>(SourceFile:4)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at io.rong.imlib.ipc.RongService.onBind(SourceFile:4)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3267)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	... 8 more
06-06 00:02:57.130  2469  2720 W JavaExceptionHandler: Too noisy! skip java exception report:com.manmolly.merchant:ipc now=1591372977129 mLastReportTime=1591372967562 interval=15000
06-06 00:02:57.152  2345  2391 I octvm_klo: klo lock
06-06 00:02:57.152  2526  2700 I WtProcessController: Receive am_crash event for pid: 6945 pkg = com.manmolly.merchant:ipc
06-06 00:02:57.152  2526  2700 W KloServer: Aborted broadcast does not supprt for: com.manmolly.merchant
06-06 00:02:57.164  2345  2391 I octvm_klo: get wanted event[mask:128, name:data_app_crash@1591372977159.txt] from the watchset
06-06 00:02:57.164  2345  2391 I octvm_klo: start gathering logcat log...
06-06 00:02:57.168  1508  1571 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@a2fa0e0
06-06 00:02:57.168  1508  1571 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@68bef99
06-06 00:02:57.183  2345  2391 I octvm_klo: gathering logcat log done
06-06 00:02:57.183  2345  2391 I octvm_klo: klo unlock
06-06 00:02:57.185   796  1604 I miuiFirewall: miui firewall always allow android
06-06 00:02:57.211  1508  6787 I Adreno  : QUALCOMM build                   : 4f3d4bc, I07a8b16b27
06-06 00:02:57.211  1508  6787 I Adreno  : Build Date                       : 10/26/17
06-06 00:02:57.211  1508  6787 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
06-06 00:02:57.211  1508  6787 I Adreno  : Local Branch                     : mybranch28842968
06-06 00:02:57.211  1508  6787 I Adreno  : Remote Branch                    : quic/gfx-adreno.lnx.1.0.r5-rel
06-06 00:02:57.211  1508  6787 I Adreno  : Remote Branch                    : NONE
06-06 00:02:57.211  1508  6787 I Adreno  : Reconstruct Branch               : NOTHING
06-06 00:02:57.224  1508  6787 I OpenGLRenderer: Initialized EGL, version 1.4
06-06 00:02:57.226  1508  6787 D OpenGLRenderer: Swap behavior 1
06-06 00:02:57.246  2062  2062 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'

```

**Comment by zoulu123** [comment]
这是我们 sdk 已经 catch 了的异常并不会导致应用崩溃的啊，你具体问下他们还有其他日志的吗？
或者具体是什么原因导致不让上的
<img width="721" alt="image" src="https://user-images.githubusercontent.com/13203373/84006066-b54ff880-a9a0-11ea-8875-8ab77075ca27.png">

**Comment by cavanlee** [comment]
日志中有很关键的一句输出：
```
06-06 00:02:57.105  6945  6945 E AndroidRuntime: Caused by: io.rong.imlib.relinker.MissingLibraryException: libdl.so
```
我想知道这个libdl.so 到底是怎么回事，很大可能就是这个引起的

**Comment by cavanlee** [comment]
我把融云IM 的插件卸载了，删除了对应的代码，重新打包，提审，小米应用市场已经审核通过。
真的希望官方重视下这个问题

**Comment by ios-yifan** [comment]
您好，当前还有遇到此问题吗？可以使用最新版本的 SDK 试一下。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
