### ISSUE TITLE
debug版本运行正常，release版本不正常，无法连接融云，也无法聊天

### ISSUE THREAD

**Issue by Meditator-K** [rongcloud/rongcloud-im-flutter-sdk#139]
Flutter 版本1.17.2，融云版本2.1.1
安卓手机测试，debug版本运行正常，release版本不正常，貌似无法连接到融云服务器，麻烦看看吧。
07-14 14:38:45.080 5997-5997/? E/[RC-Flutter-IM] Android error: getHistoryMessage-2
07-14 14:38:45.081 5997-6016/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(-2, IPC is not connected, )
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
    <asynchronous suspension>
    #2      RongIMClient.getTextMessageDraft (package:rongcloud_im_plugin/src/rong_im_client.dart:1335)
    <asynchronous suspension>
    #3      _ConversationPageState.onGetTextMessageDraft (package:yingai/im/page/conversation_page.dart:346)
    <asynchronous suspension>

**Comment by Meditator-K** [comment]
额，解决了，关掉混淆后好了。。。
