### ISSUE TITLE
上架小米应用市场，造成闪退，无法上架，附带闪退日志

### ISSUE THREAD

**Issue by cavanlee** [rongcloud/rongcloud-im-flutter-sdk#150]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/liwenzhe/flutter
    • Framework revision 0b8abb4724 (6 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/liwenzhe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 11 Pro • 4BB9ECC4-928C-4243-B890-05805E69A5FF • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```
* 异常设备是 iOS 还是 Android，列出具体机型和系统
Android 设备，Redmi Note 4X[5-V11.0.2.0.NCFCNXM]

* 提供问题发生时必要的日志，并以 txt 形式上传
```
--------- beginning of crash
08-07 01:58:34.841  7763  7763 E AndroidRuntime: FATAL EXCEPTION: main
08-07 01:58:34.841  7763  7763 E AndroidRuntime: Process: com.xiniu.manmoli:ipc, PID: 7763
08-07 01:58:34.841  7763  7763 E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service io.rong.imlib.ipc.RongService@495a5e1 with Intent { cmp=com.xiniu.manmoli/io.rong.imlib.ipc.RongService (has extras) }: io.rong.imlib.relinker.MissingLibraryException: libdl.so
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3304)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:165)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6375)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: Caused by: io.rong.imlib.relinker.MissingLibraryException: libdl.so
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.b.a(SourceFile:38)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.d(SourceFile:15)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.a(SourceFile:8)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.a(SourceFile:4)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.d(SourceFile:21)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.a(SourceFile:8)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.a(SourceFile:4)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at io.rong.imlib.NativeObject.<init>(SourceFile:3)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at gd.Yd.a(SourceFile:19)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at gd.hc.<init>(SourceFile:4)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at io.rong.imlib.ipc.RongService.onBind(SourceFile:4)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3290)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	... 8 more

```

日志中有很重要的一句话：
`08-07 01:58:34.841  7763  7763 E AndroidRuntime: Caused by: io.rong.imlib.relinker.MissingLibraryException: libdl.so
[Redmi Note 4X[5-V11.0.2.0.NCFCNXM]result8911402940410535053.txt](https://github.com/rongcloud/rongcloud-im-flutter-sdk/files/5057842/Redmi.Note.4X.5-V11.0.2.0.NCFCNXM.result8911402940410535053.txt)

`

**Comment by zoulu123** [comment]
你这是所有机型有问题还是某个机型有问题，使用的 cpu 架构是什么

**Comment by cavanlee** [comment]
找到了相关文章 https://blog.csdn.net/Alex77886/article/details/82188733 但是目前还不知道具体怎么处理。
希望官方团队可以参阅下

**Comment by chcarmen** [comment]
今天同遇到这个问题。不过是三星手机。小米上架也遇到过同样的问题。

**Comment by ios-yifan** [comment]
您好，确认一下当前是否还有遇到此问题，可以使用最新版本的 SDK 试一下。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
