### ISSUE TITLE
发送图片的问题 

### ISSUE THREAD

**Issue by freew01f** [rongcloud/rongcloud-im-flutter-sdk#187]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本 1.22
* 异常设备是 iOS 还是 Android 安卓 iOS没测
* 所调用的是什么 API  发送图片
日志如下 
```
I/[RC-Flutter-IM] Android (32563): sendMediaMessage localPath:/storage/emulated/0/Android/data/com.example.lighthouse_app/files/Pictures/scaled_image_picker9078591403043718179.jpg
W/System.err(32563): org.json.JSONException: No value for imageUri
W/System.err(32563): 	at org.json.JSONObject.get(JSONObject.java:400)
W/System.err(32563): 	at io.rong.flutter.imlib.RCIMFlutterWrapper.sendMediaMessage(RCIMFlutterWrapper.java:823)
W/System.err(32563): 	at io.rong.flutter.imlib.RCIMFlutterWrapper.sendMessage(RCIMFlutterWrapper.java:666)
W/System.err(32563): 	at io.rong.flutter.imlib.RCIMFlutterWrapper.onFlutterMethodCall(RCIMFlutterWrapper.java:161)
W/System.err(32563): 	at io.rong.flutter.imlib.RongcloudImPlugin.onMethodCall(RongcloudImPlugin.java:21)
W/System.err(32563): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err(32563): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(32563): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err(32563): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(32563): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32563): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(32563): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/[RC-Flutter-IM] Android (32563): sendMediaMessage success
I/flutter (32563): 发送图片成功 senderUserId = 1609838145017
I/flutter (32563): senderUserId : true - https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=1672824262,2727256094&fm=11&gp=0.jpg - 1609838145017
I/flutter (32563): 👻 INFO 2021-01-07 16:36:42.691058 [package:lighthouse_app/pages/conversation_page.dart 96:12 in _ConversationPageState.build] _ConversationPageState build
I/[RC-Flutter-IM] Android (32563): getConversationList success
D/RongLog (32563): [RongLog][ ImageMessage ] 缩略图为空，请检查构造图片消息的地址
[RongIMClient.MessageFactory] 该会话没有消息 type:1 targetId:1609813843787

```
现在发送图片，会报java层出错  上一个版本 不会的 
以前也不会报缩略图为空 
现在是4.1.0+1  以前晒 上一个版本 4，04

**Comment by freew01f** [comment]
这导致 extra 字段 无法携带

**Comment by kkowo** [comment]
把你加载的图片路径自己截取一下,去掉file://就行了

**Comment by freew01f** [comment]
> 把你加载的图片路径自己截取一下,去掉file://就行了

早去掉了

**Comment by kkowo** [comment]
在你图片渲染的控件处去掉,不是在设置localPath的地方去掉

**Comment by freew01f** [comment]
> 在你图片渲染的控件处去掉,不是在设置localPath的地方去掉

早就这样做了 上一个版本 没问题的

**Comment by kkowo** [comment]
这样理解吧,发送图片的一方是可以拿到本地路径的,在localpath里面直接拿,但是融云sdk,会默认给你对localpath加file://,所以你在渲染本地图片时,对融云消息localpath,进行截取,去掉flie://即可,

**Comment by kkowo** [comment]
![picture](https://user-images.githubusercontent.com/29788518/104708933-44a06400-5759-11eb-8bbf-469fc0f4c74f.png)
