### ISSUE TITLE
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/user/0/com.imetro_mobile_fl/app_lib/libRongIMLib.so"

### ISSUE THREAD

**Issue by lizaihao** [rongcloud/rongcloud-im-flutter-sdk#188]
2021-01-12 11:42:41.951 4897-4897/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.imetro_mobile_fl:ipc, PID: 4897
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/user/0/com.imetro_mobile_fl/app_lib/libRongIMLib.so"
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1632)
        at io.rong.imlib.q1.e.d(Unknown Source:0)
        at io.rong.imlib.q1.d.c(Unknown Source:183)
        at io.rong.imlib.q1.d.a(Unknown Source:21)
        at io.rong.imlib.q1.d.a(Unknown Source:1)
        at io.rong.imlib.NativeObject.<init>(Unknown Source:17)
        at io.rong.imlib.z0.a(Unknown Source:12)
        at io.rong.imlib.v0.<init>(Unknown Source:13)
        at io.rong.imlib.ipc.RongService.onBind(Unknown Source:40)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:4663)
        at android.app.ActivityThread.access$2900(ActivityThread.java:308)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2335)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by lizaihao** [comment]
生产包华为手机爆出来，小米手机没问题

**Comment by ymxz375417299** [comment]
在在/app/build.gradle
    buildTypes {
        // 发布版配置文件
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            // 必须加！ 不然融云 im插件会报错
            shrinkResources false
            minifyEnabled false

        }
    
    }

**Comment by ymxz375417299** [comment]
http://alimd.haloit.top/img/20210309112356.png

**Comment by ZhuBoao** [comment]
不能因为加了你们SDK就不能shrink了啊，应该要用一个proguard-rules -keep 保护起来吧，建议你们找一下方案

**Comment by ios-yifan** [comment]
您好，这个我们讨论确认一下，尽量在后续版本进行优化。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
