### ISSUE TITLE
安卓启动闪退

### ISSUE THREAD

**Issue by hnhcc39** [rongcloud/rongcloud-im-flutter-sdk#6]
安卓启动闪退，连不上服务器
`
        
    main Process: com.example.rongcloud_im_plugin_example:ipc, PID: 17299
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.example.rongcloud_im_plugin_example/app_lib/libRongIMLib.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1621)
        at io.rong.imlib.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
        at io.rong.imlib.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:198)
        at io.rong.imlib.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at io.rong.imlib.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at io.rong.imlib.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at io.rong.imlib.NativeObject.<init>(NativeObject.java:20)
        at io.rong.imlib.NativeClient.init(NativeClient.java:204)
        at io.rong.imlib.LibHandlerStub.<init>(LibHandlerStub.java:47)
        at io.rong.imlib.ipc.RongService.onBind(RongService.java:37)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3366)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by loginSin** [comment]
看样子是无法找到 64 位 libRongIMLib.so 文件，试着如下把 ndk 设置为 armeabi-v7a 试试
ndk {
            abiFilters "armeabi-v7a"
}
